version: '3.7'

services:
  pet-perfeito-db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "1234"
    expose:
      - "5433" # Publishes 5433 to other containers but NOT to host machine
    ports:
      - "5433:5433"
    command: -p 5433
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - postgres-compose-network

  pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "postgres@domain.local"
      PGADMIN_DEFAULT_PASSWORD: "postgres"
    ports:
      - "16543:80"
    depends_on:
      - pet-perfeito-db
    networks:
      - postgres-compose-network

networks:
  postgres-compose-network:
    driver: bridge


#https://renatogroffe.medium.com/postgresql-pgadmin-4-docker-compose-montando-rapidamente-um-ambiente-para-uso-55a2ab230b89